### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Santoshsomi** [KhalidKhattak/Adaptive-Mesh-Levelling-Cura#1]
I tried your code, but there is no way to show this into post processing script because the file placement is in wrong directory. 
it should be under `"C:\Program Files\Ultimaker Cura 4XX\plugins\PostProcessingPlugin\scripts"`

Even adding to correct path, not able to see the G29 LRFB values. Maybe some basic is missing. 
I have seen it in some other sources aswell  - https://forum.duet3d.com/topic/15302/cura-script-to-automatically-probe-only-printed-area

**Comment by KhalidKhattak** [comment]
Hi did you put G29 in the start Gcode in Cura or PRUSA slicer? Also i think you have selected the script by Pressing Add Script button ... Please let me know

**Comment by Santoshsomi** [comment]
Ya, G29 is added. 
i dont understand what you mean by selecting script? - i have the postprocessing by chaning to correct directory, added G29 and sliced gcode doesnt have modified G29.

**Comment by KhalidKhattak** [comment]
Here is my Start Gcode in Cura
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder
M140 S{material_bed_temperature_layer_0} ; Set Heat Bed temperatue
M104 S{material_print_temperature_layer_0} ; Set Extruder temperature
G28 ; Home all axes
**G29 ; Auto bed-level (BL-Touch)**
G92 E0 ; Reset Extruder
G1 Z3.0 F3000 ; move z up little to prevent scratching of surface
M109 S{material_print_temperature_layer_0} ; Wait for Extruder temperature
M190 S{material_bed_temperature_layer_0} ; Wait for Heat Bed temperature
G1 X1 Y1 Z0.3 F5000.0 ; move to start-line position
G1 X110 Y1 Z0.3 F1500.0 E15 ; draw 1st line
G92 E0 ; reset extruder
G1 Z1.0 F3000 ; move z up little to prevent scratching of surface

**Comment by Santoshsomi** [comment]
ok, so show me the processed gcode after the script works for you?

**Comment by KhalidKhattak** [comment]
wait i am in office..but For the script directory you must verify from HELP menu.. can you share the help menu screenshot of your Cura?

**Comment by KhalidKhattak** [comment]
Also when you copy the Script file in the SCRIPT directory you have to exit the cura and run it again.
After you restart cura , you have to go to CURA menu EXTENSIONS-- POSTPROCESSING---MODIFIY GCODE--(A window will appear)---PRESS ADD SCRIPT BUTTON---SELECT LEVELLING MESH OPTIMIZER IT IS HARDCODED WITH +6MM ALL AROUND THE OBJECT BOUNDING BOX

**Comment by KhalidKhattak** [comment]
I will make a short video today and upload on youtube...

**Comment by Santoshsomi** [comment]
> Also when you copy the Script file in the SCRIPT directory you have to exit the cura and run it again. After you restart cura , you have to go to CURA menu EXTENSIONS-- POSTPROCESSING---MODIFIY GCODE--(A window will appear)---PRESS ADD SCRIPT BUTTON---SELECT LEVELLING MESH OPTIMIZER IT IS HARDCODED WITH +6MM ALL AROUND THE OBJECT BOUNDING BOX

i know how to use post-process plugin, but yours not working.  Ok lets see your video once. and share your gcode once its modified by script automatically.

**Comment by KhalidKhattak** [comment]
Here is the video link
[https://www.youtube.com/watch?v=QksjSpTgaGU](url)

**Comment by Santoshsomi** [comment]
> https://www.youtube.com/watch?v=QksjSpTgaGU

Works only with latest Cura 5xx. But Version 4XX doesnt work with placement of script.

**Comment by KhalidKhattak** [comment]
Thanks the problem is resolved.. i am not an expert in Python script..i hope some minor changes will be required to implement on old cura version.
